# Generated by Django 3.2.3 on 2021-05-28 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ad',
            new_name='Advertising',
        ),
    ]
