# Generated by Django 3.2.3 on 2021-05-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_ad_advertising'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.URLField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ManyToManyField(related_name='publicity_image', to='api.Image')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Рекламы',
            },
        ),
        migrations.DeleteModel(
            name='Advertising',
        ),
    ]
