# Generated by Django 3.2.3 on 2021-06-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210528_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, related_name='advert_image', to='api.Image'),
        ),
        migrations.AlterField(
            model_name='publicity',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, related_name='publicity_image', to='api.Image'),
        ),
    ]
