# Generated by Django 3.2.3 on 2021-06-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210602_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ManyToManyField(related_name='advert_image', to='api.Image'),
        ),
        migrations.AlterField(
            model_name='publicity',
            name='image',
            field=models.ManyToManyField(related_name='publicity_image', to='api.Image'),
        ),
    ]
