# Generated by Django 3.2.3 on 2021-06-07 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210602_0305'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='custom_user',
        ),
    ]
