# Generated by Django 3.2.3 on 2021-06-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='api_user',
        ),
    ]
